name: tetris_classic
description: Tetris Classic Game
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0' # رفعنا النسخة عشان تدعم ميزات Dart الجديدة

dependencies:
  flutter:
    sdk: flutter
  # رفعنا إصدارات Flame عشان تتوافق مع الـ Rendering والـ Audio اللي استعملناه
  flame: ^1.23.0 
  flame_audio: ^2.10.7
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/