name: Build and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4 # تحديث لـ v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Build Android APK
        run: flutter build apk --debug

      - name: Build Windows EXE
        run: flutter build windows --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4 # ده التغيير الجوهري لـ v4
        with:
          name: game-builds
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/windows/runner/Release/*.exe
            build/web/
