name: Build and Release

on:
  push:
    branches: [ main ] # أو master حسب اسم الفرع عندك

jobs:
  build:
    runs-on: windows-latest # بنستخدم ويندوز عشان يطلع لنا EXE و APK في نفس الوقت

    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Build Android APK
        run: flutter build apk --debug # debug أسرع في البناء للتجربة

      - name: Build Windows EXE
        run: flutter build windows --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: game-builds
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/windows/runner/Release/*.exe
            build/web/